global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: node
    static_configs:
      # node-exporter está em network_mode: host; use localhost:9100 do host
      - targets: ["localhost:9100"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: postgres
    static_configs:
      - targets: ["postgres_exporter:9187"]

  - job_name: mongodb
    static_configs:
      - targets: ["mongodb_exporter:9216"]

  - job_name: redis
    static_configs:
      - targets: ["redis_exporter:9121"]
